pipeline{
    agent any

    tools{
        maven 'Maven 3.8.6'
    }
    stages{
        stage('build'){
            steps{
                echo 'Compiling worker app'
                dir('worker'){
                    sh 'mvn compile'
                }
            }
        }
        stage('test'){
            steps{
                echo 'Running unit tests on worker app'
                dir('worker'){
                    sh 'mvn clean test'
                }
            }
        }
        stage('package'){
            steps{
                echo 'Packaging worker app'
                dir('worker'){
                    sh 'mvn package'
                }
            }
        }
    }

    post{
        always{
            echo 'The pipeline run has completed...'
        }
    }
}